[general]
app_name = "app1"

[development]
directory = "src_dev"

[deploy.gitbranch]
prod = "main"
beta = "main"

[deploy.staging]
directory = "staging"

[deploy.local]
directory = "src_test_webserver/shinyapps/"
base_url = "localhost:8000/apps"

[deploy.server]
host = "testserver"
user = "testuser"
directory = "/homes/user/docker_volumes/shinyapps/"
base_url = "https://realurl.com/apps"