[general]
app_name = "app1"

[development]
directory = "src/app1"

[deploy.gitbranch]
prod = "main"
beta = "main"

[deploy.staging]
directory = "staging"

[deploy.local]
directory = "test_webserver/shinyapps/"
base_url = "localhost:8000/apps"

[deploy.server]
host = "127.0.0.1"
user = "shinylive"
port = 2222
directory = "shinyapps"
base_url = "http://localhost:5000"